FROM python:3.12-slim


WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

#COPY ./backend/req.txt ./
#RUN pip install --upgrade pip && pip install -r req.txt
#
COPY ./backend/req.txt /app/req.txt
RUN pip install --no-cache-dir --upgrade pip && pip install --no-cache-dir -r /app/req.txt


# Копируем backend внутрь /app/backend
COPY backend /app/backend


#EXPOSE 8000

ENV PYTHONPATH=/app

#CMD ["sh", "-c", "apt-get update && apt-get install -y tree && tree /app && uvicorn backend.main:app --host 0.0.0.0 --port 8000"]

CMD ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000"]
