"""fix

Revision ID: 0f3f732c0d0e
Revises: f4f96a1635b0
Create Date: 2025-07-16 16:19:26.670809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f3f732c0d0e'
down_revision: Union[str, Sequence[str], None] = 'f4f96a1635b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('problem_card', 'problem_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('problem_card_problem_id_fkey'), 'problem_card', type_='foreignkey')
    op.drop_constraint(op.f('problem_card_quiz_field_id_fkey'), 'problem_card', type_='foreignkey')
    op.create_foreign_key(None, 'problem_card', 'problem', ['problem_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'problem_card', 'quiz_field', ['quiz_field_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('quiz_field_contest_id_fkey'), 'quiz_field', type_='foreignkey')
    op.create_foreign_key(None, 'quiz_field', 'contest', ['contest_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quiz_field', type_='foreignkey')
    op.create_foreign_key(op.f('quiz_field_contest_id_fkey'), 'quiz_field', 'contest', ['contest_id'], ['id'])
    op.drop_constraint(None, 'problem_card', type_='foreignkey')
    op.drop_constraint(None, 'problem_card', type_='foreignkey')
    op.create_foreign_key(op.f('problem_card_quiz_field_id_fkey'), 'problem_card', 'quiz_field', ['quiz_field_id'], ['id'])
    op.create_foreign_key(op.f('problem_card_problem_id_fkey'), 'problem_card', 'problem', ['problem_id'], ['id'])
    op.alter_column('problem_card', 'problem_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
