"""update

Revision ID: 1900d3170529
Revises: b8b411818c89
Create Date: 2025-07-24 15:48:52.640655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1900d3170529'
down_revision: Union[str, Sequence[str], None] = 'b8b411818c89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('selected_problem_id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(length=32), nullable=False),
    sa.Column('verdict', sa.Enum('ACCEPTED', 'WRONG', 'REJECTED', name='submissionverdict'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['selected_problem_id'], ['selected_problem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submission')
    # ### end Alembic commands ###
