"""update selected_problem with contestant_id

Revision ID: 649aa1517582
Revises: aa4f05e84cfb
Create Date: 2025-07-20 22:06:10.457147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '649aa1517582'
down_revision: Union[str, Sequence[str], None] = 'aa4f05e84cfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('selected_problem', sa.Column('contestant_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'selected_problem', 'contestant', ['contestant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'selected_problem', type_='foreignkey')
    op.drop_column('selected_problem', 'contestant_id')
    # ### end Alembic commands ###
