"""fix

Revision ID: 6b74f03e595f
Revises: 0f3f732c0d0e
Create Date: 2025-07-16 16:47:09.058080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b74f03e595f'
down_revision: Union[str, Sequence[str], None] = '0f3f732c0d0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'quiz_field', ['contest_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quiz_field', type_='unique')
    # ### end Alembic commands ###
