"""fix constrains

Revision ID: 95856a36e683
Revises: 8c3036cb0399
Create Date: 2025-07-16 16:02:14.513579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95856a36e683'
down_revision: Union[str, Sequence[str], None] = '8c3036cb0399'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_check_constraint(
        constraint_name="check_start_points",
        table_name="contest",
        condition="start_points BETWEEN 0 AND 10000"
    )
    op.create_check_constraint(
        constraint_name="check_number_of_slots",
        table_name="contest",
        condition="number_of_slots_for_problems BETWEEN 1 AND 5"
    )
    op.create_check_constraint(
        constraint_name="check_category_price",
        table_name="problem_card",
        condition="category_price BETWEEN 0 AND 10000"
    )
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
