"""update selected_problem

Revision ID: bb816cc478a9
Revises: ea76ec7697ba
Create Date: 2025-07-22 12:27:04.652695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb816cc478a9'
down_revision: Union[str, Sequence[str], None] = 'ea76ec7697ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('selected_problem', 'reward_rule')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('selected_problem', sa.Column('reward_rule', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
