"""user-add-cols

Revision ID: bea8b507a27c
Revises: 6b74f03e595f
Create Date: 2025-07-17 14:01:20.127244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bea8b507a27c'
down_revision: Union[str, Sequence[str], None] = '6b74f03e595f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('domain_number', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('uuid', sa.String(length=36), nullable=False))
    op.create_unique_constraint('uq_user_domain_username', 'user', ['domain_number', 'username'])
    op.create_unique_constraint(None, 'user', ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint('uq_user_domain_username', 'user', type_='unique')
    op.drop_column('user', 'uuid')
    op.drop_column('user', 'domain_number')
    # ### end Alembic commands ###
