"""update

Revision ID: d9ec2e509f1e
Revises: 1900d3170529
Create Date: 2025-07-24 15:59:00.496048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd9ec2e509f1e'
down_revision: Union[str, Sequence[str], None] = '1900d3170529'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    contest_rule_type_enum = postgresql.ENUM('ACTIVE', 'SOLVED', 'FAILED', 'REJECTED', name='selectedproblemstatustype')
    contest_rule_type_enum.create(op.get_bind())
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
