"""update selected_problem

Revision ID: ea76ec7697ba
Revises: 649aa1517582
Create Date: 2025-07-20 22:13:05.642641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea76ec7697ba'
down_revision: Union[str, Sequence[str], None] = '649aa1517582'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "CREATE TYPE selectedproblemstatustype AS ENUM ('ACTIVE', 'SOLVED', 'REJECTED')"
    )
    op.add_column('selected_problem', sa.Column('status', sa.Enum('ACTIVE', 'SOLVED', 'REJECTED', name='selectedproblemstatustype'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('selected_problem', 'status')
    # ### end Alembic commands ###
